from __future__ import annotations

from idiom_video.schemas import IdiomProfile, Script, ScriptScene, SpeechCue


def _cue(
    cue_id: str,
    scene_id: str,
    speaker_id: str,
    speaker_name: str,
    kind: str,
    text: str,
    emotion: str,
    mouth_action: str,
    duration: float,
) -> SpeechCue:
    return SpeechCue(
        cue_id=cue_id,
        scene_id=scene_id,
        speaker_id=speaker_id,
        speaker_name=speaker_name,
        kind=kind,
        voice_text=text,
        subtitle_text=text,
        emotion=emotion,
        mouth_action=mouth_action,
        lip_sync_required=False,
        estimated_start_seconds=0.0,
        estimated_end_seconds=duration,
    )


def build_script(profile: IdiomProfile) -> Script:
    farmer = next((char for char in profile.characters if char.id == "farmer_amu"), profile.characters[0])
    rabbit = next((char for char in profile.characters if char.id == "rabbit"), None)
    rabbit_name = rabbit.name if rabbit is not None else "小兔"
    scenes = [
        ScriptScene(
            scene_id="scene_01",
            order=1,
            title="清晨耕田",
            summary="阿木认真耕田，轻松建立勤劳的起点。",
            visual_goal="建立古代农田、树桩和主角形象。",
            duration_seconds=5.0,
            speech_cues=[
                _cue(
                    "scene_01_narration",
                    "scene_01",
                    "narrator",
                    "旁白",
                    "narration",
                    "很久以前，有个农夫叫阿木，每天都认真在田里干活。",
                    "warm",
                    "none",
                    2.5,
                ),
                _cue(
                    "scene_01_dialogue",
                    "scene_01",
                    farmer.id,
                    farmer.name,
                    "dialogue",
                    "今天的地也要好好翻，庄稼才会听话。",
                    "cheerful",
                    "speaking_simple",
                    2.5,
                ),
            ],
        ),
        ScriptScene(
            scene_id="scene_02",
            order=2,
            title="小兔跑来",
            summary="小兔慌慌张张跑过田边小路。",
            visual_goal="用轻松动作引出偶然事件。",
            duration_seconds=4.0,
            speech_cues=[
                _cue(
                    "scene_02_narration",
                    "scene_02",
                    "narrator",
                    "旁白",
                    "narration",
                    f"这时，{rabbit_name}从小路边跑来，快得像一团灰色小风。",
                    "playful",
                    "none",
                    4.0,
                )
            ],
        ),
        ScriptScene(
            scene_id="scene_03",
            order=3,
            title="树桩惊喜",
            summary="小兔停在树桩旁，阿木惊讶又开心。",
            visual_goal="温和表现偶然事件，不夸张，适合儿童观看。",
            duration_seconds=5.0,
            speech_cues=[
                _cue(
                    "scene_03_narration",
                    "scene_03",
                    "narrator",
                    "旁白",
                    "narration",
                    "小兔跑得太急，轻轻撞到树桩，晕乎乎地躺在树桩旁，把阿木吓了一跳。",
                    "surprised",
                    "none",
                    2.5,
                ),
                _cue(
                    "scene_03_dialogue",
                    "scene_03",
                    farmer.id,
                    farmer.name,
                    "dialogue",
                    "咦？田边还会自己送惊喜？",
                    "surprised",
                    "speaking_simple",
                    2.5,
                ),
            ],
        ),
        ScriptScene(
            scene_id="scene_04",
            order=4,
            title="好运误会",
            summary="阿木把偶然当成固定方法。",
            visual_goal="让观众看出阿木把偶然当成方法。",
            duration_seconds=5.0,
            speech_cues=[
                _cue(
                    "scene_04_dialogue",
                    "scene_04",
                    farmer.id,
                    farmer.name,
                    "dialogue",
                    "这好运气是不是认识路？明天会不会还来？",
                    "hopeful",
                    "speaking_simple",
                    5.0,
                )
            ],
        ),
        ScriptScene(
            scene_id="scene_05",
            order=5,
            title="幻想排队",
            summary="阿木想象兔子会排队来，笑点来自憨厚误会。",
            visual_goal="用想象画面表现侥幸心理，保持轻松好笑。",
            duration_seconds=5.0,
            speech_cues=[
                _cue(
                    "scene_05_dialogue",
                    "scene_05",
                    farmer.id,
                    farmer.name,
                    "dialogue",
                    "要是一只接一只来，我连篮子都得准备大一点！",
                    "dreamy",
                    "speaking_simple",
                    5.0,
                )
            ],
        ),
        ScriptScene(
            scene_id="scene_06",
            order=6,
            title="搬凳等待",
            summary="阿木带着小板凳守在树桩旁。",
            visual_goal="表现等待和田地被忽略，笑点来自准备过于认真。",
            duration_seconds=6.0,
            speech_cues=[
                _cue(
                    "scene_06_narration",
                    "scene_06",
                    "narrator",
                    "旁白",
                    "narration",
                    "第二天，阿木搬来小板凳，认真得像要参加一场等兔子比赛。",
                    "concerned",
                    "none",
                    6.0,
                )
            ],
        ),
        ScriptScene(
            scene_id="scene_07",
            order=7,
            title="落叶虚惊",
            summary="风吹落叶，阿木误以为兔子来了。",
            visual_goal="用温和误会制造轻喜剧节奏。",
            duration_seconds=5.0,
            speech_cues=[
                _cue(
                    "scene_07_dialogue",
                    "scene_07",
                    farmer.id,
                    farmer.name,
                    "dialogue",
                    "来了来了！哎呀，原来是一片叶子。",
                    "comic_surprise",
                    "speaking_simple",
                    5.0,
                )
            ],
        ),
        ScriptScene(
            scene_id="scene_08",
            order=8,
            title="田地荒了",
            summary="兔子没有再来，田里的庄稼越来越差。",
            visual_goal="温和展示错误选择的结果。",
            duration_seconds=6.0,
            speech_cues=[
                _cue(
                    "scene_08_dialogue",
                    "scene_08",
                    farmer.id,
                    farmer.name,
                    "dialogue",
                    "兔子怎么还不来？我的田倒是先打了瞌睡。",
                    "worried",
                    "speaking_simple",
                    6.0,
                )
            ],
        ),
        ScriptScene(
            scene_id="scene_09",
            order=9,
            title="阿木醒悟",
            summary="阿木发现兔子不会每天来，明白等待不可靠。",
            visual_goal="让角色自己说出错误在哪里。",
            duration_seconds=5.0,
            speech_cues=[
                _cue(
                    "scene_09_dialogue",
                    "scene_09",
                    farmer.id,
                    farmer.name,
                    "dialogue",
                    "原来兔子不会每天打卡，地也不会自己长好。",
                    "realizing",
                    "speaking_simple",
                    5.0,
                )
            ],
        ),
        ScriptScene(
            scene_id="scene_10",
            order=10,
            title="重新耕田",
            summary="阿木重新拿起农具，明白不能靠等待生活。",
            visual_goal="给出积极结尾和成语寓意。",
            duration_seconds=5.0,
            speech_cues=[
                _cue(
                    "scene_10_narration",
                    "scene_10",
                    "narrator",
                    "旁白",
                    "narration",
                    f"这就是{profile.idiom}。偶然的好运不能代替勤劳和思考。",
                    "clear",
                    "none",
                    5.0,
                )
            ],
        ),
    ]
    return Script(
        idiom_slug=profile.slug,
        title=profile.idiom,
        moral=profile.moral,
        characters=profile.characters,
        scenes=scenes,
    )
